CREATE TABLE email_service_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ratio INT NOT NULL,
    is_active BOOLEAN NOT NULL
);

CREATE TABLE test_send_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    total_requests INT NOT NULL
);

CREATE TABLE test_send_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_provider_name VARCHAR(255) NOT NULL,
    sent_count INT NOT NULL,
    test_send_run_id BIGINT NOT NULL,
    FOREIGN KEY (test_send_run_id) REFERENCES test_send_run(id)
);
